name: Compile and Evaluate

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Git user
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Set up C++
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Install time utility
      run: sudo apt-get install -y time

    - name: Debug directory structure
      run: |
        echo "Listing root directory"
        ls -R

    - name: Compile and evaluate programs
      run: |
        for sheet in Sheet*; do
          echo "Running $sheet"
          if [ -d "$sheet/Submissions" ]; then
            echo "Submissions directory found in $sheet"
            for subdir in "$sheet/Submissions"/*; do
              if [ -d "$subdir" ]; then
                echo "Processing $subdir"
                for file in "$subdir"/*.cpp; do
                  if [ -f "$file" ]; then
                    echo "Compiling $file"
                    g++ -o "${file%.cpp}" "$file"
                    if [ $? -eq 0 ]; then
                      echo "Running ${file%.cpp}"
                      result=$(/usr/bin/time -v ./"${file%.cpp}" 2>&1)
                      echo "$result" > "${subdir}/README.md"
                    else
                      echo "Compilation failed for $file" > "${subdir}/README.md"
                    fi
                  else
                    echo "No .cpp files found in $subdir"
                  fi
                done
              else
                echo "$subdir is not a directory"
              fi
            done
          else
            echo "No Submissions folder found in $sheet"
          fi
        done

    - name: Commit results
      run: |
        git add Sheet*/Submissions/*/README.md
        git commit -m 'Update evaluation results' || echo "No changes to commit"
        git pull --rebase
        git push
